export const NAV = {
  ONBOARDING: 'ONBOARDING',
  MAIN_BOTTOM_NAVIGATOR: 'MAIN_BOTTOM_NAVIGATOR',

  // Onboarding
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',

  // Main Bottom Tabs
  VOICE_TRANSCRIBE_PAGE: 'VOICE_TRANSCRIBE_PAGE',
  DETECT_SENTIMENT_PAGE: 'DETECT_SENTIMENT_PAGE',
  PROFILE_PAGE: 'PROFILE_PAGE',
};
