export const NAV = {
  ONBOARDING: 'ONBOARDING',
  MAIN_BOTTOM_NAVIGATOR: 'MAIN_BOTTOM_NAVIGATOR',

  // Onboarding
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',

  // Main Bottom Tabs
  MOVIES_PAGE: 'MOVIES_PAGE',
  SHOWS_PAGE: 'SHOWS_PAGE',
  PROFILE_PAGE: 'PROFILE_PAGE',
};
